#!/usr/bin/env bash
# i change the ip in ect/hosts of localhost and facebook
sudo cp /etc/hosts /etc/hosts.old
sudo sed -i 's/127.0.0.1/127.0.0.2/tlocalhost/' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts
echo -e '8.8.8.8 facebook.com' | sudo tee -a /etc/hosts
