#!/usr/bin/env bash
# i change the port in ect/hosts of localhost and facebook
cp /etc/hosts /etc/hosts.old
sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts
echo '8.8.8.8 facebook.com' | sudo tee -a /etc/hosts
